# Generated by Django 5.1 on 2024-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0002_alter_registers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=200)),
                ('suggestions', models.CharField(max_length=300)),
                ('positive_aspects', models.CharField(max_length=300)),
                ('areas_for_improvement', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Registers',
        ),
    ]
