# Generated by Django 5.1.1 on 2024-10-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphan', '0004_feedbackforms_futuresupport_userdonate'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdonatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('d_item', models.TextField()),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='userdonate',
        ),
    ]
